// \ud83d\udd01 Generated by Damien Edward Featherstone // No_Gas_Labs\u2122
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
});
