-- // \ud83d\udd01 Generated by Damien Edward Featherstone // No_Gas_Labs\u2122
create table users (
  id uuid primary key,
  wallet text,
  telegram_id text
);

create table xp_state (
  user_id uuid references users(id),
  current_xp int,
  scrolls_unlocked int
);

create table relics (
  relic_id uuid primary key,
  user_id uuid references users(id),
  tier int,
  date_claimed timestamp
);

create table prophecy_log (
  user_id uuid references users(id),
  xp_at_unlock int,
  message text
);
