-- // 🔁 Generated by Damien Edward Featherstone // No_Gas_Labs™
create table if not exists users (
  id uuid primary key,
  wallet text,
  telegram_id text
);

create table if not exists xp_state (
  user_id uuid references users(id),
  current_xp int,
  scrolls_unlocked int
);

create table if not exists relics (
  relic_id uuid primary key,
  user_id uuid references users(id),
  tier text,
  date_claimed timestamp
);

create table if not exists prophecy_log (
  user_id uuid references users(id),
  xp_at_unlock int,
  message text
);
