# // \ud83d\udd01 Generated by Damien Edward Featherstone // No_Gas_Labs\u2122
from aiogram import Bot, Dispatcher, types
from aiogram.utils import executor

BOT_TOKEN = 'CHANGE_ME'
bot = Bot(token=BOT_TOKEN)
dp = Dispatcher(bot)

@dp.message_handler(commands=['start'])
async def start(msg: types.Message):
    await msg.reply('Summon complete')

if __name__ == '__main__':
    executor.start_polling(dp)
