// 🔁 Generated by Damien Edward Featherstone // No_Gas_Labs™
import React, { useState, useEffect } from "react";
import { createClient } from "@supabase/supabase-js";

const supabase = createClient("/supabase-url", "/supabase-key");

export default function App() {
  const [xp, setXp] = useState(0);
  const [wallet, setWallet] = useState(null);

  useEffect(() => {
    const stored = localStorage.getItem("xp");
    if (stored) setXp(parseInt(stored));
  }, []);

  const tapShrine = () => {
    const newXp = xp + 1;
    setXp(newXp);
    localStorage.setItem("xp", newXp);
    supabase.from("xp_state").upsert({ user_id: wallet || "anon", current_xp: newXp });
  };

  return (
    <div>
      <h1>Shrine XP: {xp}</h1>
      <button onClick={tapShrine}>Tap Shrine</button>
      <div>
        <button onClick={() => setWallet("TON")}>TON</button>
        <button onClick={() => setWallet("EOS")}>EOS</button>
        <button onClick={() => setWallet("SUI")}>SUI</button>
      </div>
    </div>
  );
}
