# // 🔁 Generated by Damien Edward Featherstone // No_Gas_Labs™
from aiogram import Bot, Dispatcher, executor, types
import os

API_TOKEN = os.getenv("XP_SUMMONER_TOKEN", "")
bot = Bot(token=API_TOKEN)
dp = Dispatcher(bot)

@dp.message_handler(commands=["start"])
async def start(message: types.Message):
    await message.answer("Daily summon complete. +10 XP")

if __name__ == "__main__":
    executor.start_polling(dp)
