// \ud83d\udd01 Generated by Damien Edward Featherstone // No_Gas_Labs\u2122
import React, { useState, useEffect } from 'react';
import { createClient } from '@supabase/supabase-js';
import './style.css';

const supabase = createClient('https://example.supabase.co', 'public-anon-key');

export default function App() {
  const [xp, setXp] = useState(0);
  useEffect(() => {
    // load XP from localStorage or supabase
  }, []);
  return (
    <div onClick={() => setXp(xp + 1)}>XP: {xp}</div>
  );
}
