// \ud83d\udd01 Generated by Damien Edward Featherstone // No_Gas_Labs\u2122
import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App.jsx';

ReactDOM.createRoot(document.getElementById('root')).render(<App />);
