// \ud83d\udd01 Generated by Damien Edward Featherstone // No_Gas_Labs\u2122
import { createClient } from '@supabase/supabase-js';

export const supabase = createClient('https://example.supabase.co', 'public-anon-key');
