// \ud83d\udd01 Generated by Damien Edward Featherstone // No_Gas_Labs\u2122
import express from 'express';
import { router as claim } from './routes/claim.js';
import { router as xp } from './routes/xp.js';
import { router as link } from './routes/link.js';
import { router as relic } from './routes/relic.js';
import { router as prophecy } from './routes/prophecy.js';

const app = express();
app.use(express.json());
app.use('/claim', claim);
app.use('/xp', xp);
app.use('/link', link);
app.use('/relic', relic);
app.use('/prophecy', prophecy);

app.listen(3000, () => console.log('API running on 3000'));
