// 🔁 Generated by Damien Edward Featherstone // No_Gas_Labs™
import { supabase } from "../supabase/supabase.js";

async function load() {
  const { data } = await supabase.from("users").select("id, wallet");
  const container = document.getElementById("users");
  container.innerHTML = (data || []).map(u => `<p>${u.id} - ${u.wallet}</p>`).join("");
}

load();
