# // 🔁 Generated by Damien Edward Featherstone // No_Gas_Labs™
from aiogram import Bot, Dispatcher, executor, types
import os

API_TOKEN = os.getenv("RELIC_VENDOR_TOKEN", "")
bot = Bot(token=API_TOKEN)
dp = Dispatcher(bot)

@dp.message_handler(commands=["mint"])
async def mint(message: types.Message):
    await message.answer("Relic minted!")

if __name__ == "__main__":
    executor.start_polling(dp)
