name: HTML verify
on:
  push:
  pull_request:
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with: { python-version: '3.x' }
      - run: pip install html5validator
      - run: html5validator --root . --also-check-css --blacklist ".git,.github"
